### ISSUE TITLE
When I can't get X from Y, is that a TODO, a limitation of the database, or just non-sensical?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#14]
| `where=...`       | `cell`    | `cluster` | `dataset` | `gene`    | `organ`   | `protein` |
| ----------------- | --------- | --------- | --------- | --------- | --------- | --------- |
| [`select_cells()`](https://github.com/hubmapconsortium/cells-api-py-client/blob/main/examples/select_cells.md)    |           |           | ✓         | ✓         | ✓         | ✓         |
| [`select_clusters()`](https://github.com/hubmapconsortium/cells-api-py-client/blob/main/examples/select_clusters.md) |           |           |           | ✓         |           |           |
| ~~`select_datasets()`~~ |           |           |           |           |           |           |
| [`select_genes()`](https://github.com/hubmapconsortium/cells-api-py-client/blob/main/examples/select_genes.md)    |           | ✓         |           |           | ✓         |           |
| [`select_organs()`](https://github.com/hubmapconsortium/cells-api-py-client/blob/main/examples/select_organs.md)   | ✓         |           |           | ✓         |           |           |
| ~~`select_proteins()`~~ |           |           |           |           |           |           |

- `cells`:
  - [ ] `select_cells(where='cell', ...)`?
  - [ ] `select_cells(where='cluster', ...)`?
- `clusters`:
  - [ ] `select_clusters(where='cell', ...)`?
  - [ ] `select_clusters(where='cluster', ...)`?
  - [ ] `select_clusters(where='dataset', ...)`?
  - [ ] `select_clusters(where='organ', ...)`?
  - [ ] `select_clusters(where='protein', ...)`?
- `datasets`
  - [ ] `select_datasets(...)`?
- `genes`:
  - [ ] `select_genes(where='cell', ...)`?
  - [ ] `select_genes(where='dataset', ...)`?
  - [ ] `select_genes(where='gene', ...)`?
  - [ ] `select_genes(where='protein', ...)`?
- `organs`:
  - [ ] `select_organs(where='cluster', ...)`?
  - [ ] `select_organs(where='dataset', ...)`?
  - [ ] `select_organs(where='organ', ...)`?
  - [ ] `select_organs(where='protein', ...)`?
- `proteins`
  - [ ] `select_proteins(...)`?

**Comment by SFD5311** [comment]
I would say in most cases, it's because a meaningful definition of that query hasn't been suggested yet.  Because the database and the code that processes data for the database are being created and updated in tandem with the API, I think there's not a super meaningful distinction between limitations of the database and TODOs.  Things would be either limits of the source data (like the lack of cell types), or TODO.  But again, I'd say most types of query that aren't implemented aren't because no meaningful definition has yet been suggested.

**Comment by mccalluc** [comment]
(See also #25 ... python-api could hit other rest-apis to make this a one-stop shop.)

**Comment by SFD5311** [comment]
Good point.  I think going over this meeting and soliciting additional query definitions good be another item for the agenda for the meeting next week.
